// lesson.ts

// 2.3 Return Values
// Base exercise file
// Do not edit this file after creation.
// Create your own version file for answers.

// Fast Rule:
// return sends a value back from a function.

// Drill 1
// Create a function named getAge.
// It should return the number 35.
function getAge () {
  return 35;
}

// Drill 2
// Create a function named multiply.
// It should take 2 number parameters.
// It should return their product.
function multiply (x: number, y: number) {
  const product: number = x * y;
  return product;
}

// Drill 3
// Create a function named getFirstTask.
// It should take an array of strings.
// It should return the first item in the array.
function getFirstTask(strings: Array<string>) {
  const firstItem = strings[0];
  return firstItem;
}

// Drill 4
// In 1–2 lines, explain:
// What is the difference between console.log() and return?
// console.log prints something, mostly used in logging while return actually returns a value from the function, which can be used, saved.

// Main Task
// Fix the function below so message gets the correct value.

function getWelcomeMessage(name: string) {
  // console.log("Welcome, " + name);
  const welcomeMessage = "Welcome, " + name;
  return welcomeMessage;
}

const message = getWelcomeMessage("Arvin");
console.log(message);

// Debug Check
// Look at the broken code below.
// Write what is wrong.
// Then create your own fixed version in your attempt file.

function getTotal(a: number, b: number): number {
  const sum = a + b;
  return sum;
}

const finalTotal = getTotal(4, 6);
console.log(finalTotal);

// Meeting Answer
// Write a short explanation:
// What is a return value?
// a return value is an expression that returns intended return value of the function to the caller.

// Perfect Explanation
// Write the most precise 1–2 line explanation you can.
// a return value is an expression that returns intended return value of the function to the caller.
