// // lesson.ts

// // 2.3 Return Values
// // Base exercise file
// // Do not edit this file after creation.
// // Create your own version file for answers.

// // Fast Rule:
// // return sends a value back from a function.

// // Drill 1
// // Create a function named getAge.
// // It should return the number 35.

// // Drill 2
// // Create a function named multiply.
// // It should take 2 number parameters.
// // It should return their product.

// // Drill 3
// // Create a function named getFirstTask.
// // It should take an array of strings.
// // It should return the first item in the array.

// // Drill 4
// // In 1–2 lines, explain:
// // What is the difference between console.log() and return?

// // Main Task
// // Fix the function below so message gets the correct value.

// function getWelcomeMessage(name: string) {
//   console.log("Welcome, " + name);
// }

// const message = getWelcomeMessage("Arvin");
// console.log(message);

// // Debug Check
// // Look at the broken code below.
// // Write what is wrong.
// // Then create your own fixed version in your attempt file.

// function getTotal(a: number, b: number): number {
//   const sum = a + b;
// }

// const finalTotal = getTotal(4, 6);
// console.log(finalTotal);

// // Meeting Answer
// // Write a short explanation:
// // What is a return value?

// // Perfect Explanation
// // Write the most precise 1–2 line explanation you can.

